import type { StoredSession } from "@/hooks/useAudioStore";

/**
 * Seed demo sessions pre-loaded on first visit so users can
 * immediately explore the full pipeline without recording first.
 */
export const SEED_SESSIONS: StoredSession[] = [
    {
        id: "demo-mixtec-greetings",
        fileName: "mixtec_greetings_field_001.wav",
        language: "Mixtec",
        segmentCount: 6,
        avgConfidence: 88,
        durationSeconds: 42.5,
        model: "Allosaurus (uni2005)",
        createdAt: "2026-02-28T14:30:00.000Z",
        segments: [
            {
                id: "seg-m1",
                time: "00:00:02",
                startTime: 1.8,
                endTime: 4.2,
                speaker: "Speaker A",
                ipa: "na.ˈsa.a",
                meaning: "good morning",
                confidence: 92,
                culturalContext: "Standard Mixtec greeting used in San Juan Mixtepec. The rising tone on the final syllable signals formality.",
            },
            {
                id: "seg-m2",
                time: "00:00:05",
                startTime: 4.5,
                endTime: 7.1,
                speaker: "Speaker A",
                ipa: "ˈnda.vi.ko.jo",
                meaning: "rain",
                confidence: 87,
                culturalContext: "Often used as a conversational opener — checking weather conditions is culturally significant in agricultural communities.",
            },
            {
                id: "seg-m3",
                time: "00:00:09",
                startTime: 8.0,
                endTime: 12.3,
                speaker: "Speaker B",
                ipa: "ˈku.ni ˈsa.a",
                meaning: "I want to eat",
                confidence: 84,
                culturalContext: "",
            },
            {
                id: "seg-m4",
                time: "00:00:15",
                startTime: 14.2,
                endTime: 18.5,
                speaker: "Speaker A",
                ipa: "ˈi.tʃi ˈñu.ʔu",
                meaning: "inside the house",
                confidence: 91,
                culturalContext: "The nasalized /ñ/ is characteristic of the Mixtepec variety. Other Mixtec dialects use /n/ here.",
            },
            {
                id: "seg-m5",
                time: "00:00:22",
                startTime: 21.0,
                endTime: 26.8,
                speaker: "Speaker B",
                ipa: "ˈna.na ˈsa.tʃi",
                meaning: "mother is cooking",
                confidence: 89,
                culturalContext: "The verb form implies ongoing action, similar to present progressive in English.",
            },
            {
                id: "seg-m6",
                time: "00:00:30",
                startTime: 29.5,
                endTime: 34.0,
                speaker: "Speaker A",
                ipa: "ˈta.ta ˈku.a.ʔa",
                meaning: "father went away",
                confidence: 85,
                culturalContext: "",
            },
        ],
    },
    {
        id: "demo-mixtec-market",
        fileName: "mixtec_market_vocabulary_002.wav",
        language: "Mixtec",
        segmentCount: 5,
        avgConfidence: 86,
        durationSeconds: 35.0,
        model: "Allosaurus (uni2005)",
        createdAt: "2026-03-01T10:15:00.000Z",
        segments: [
            {
                id: "seg-mk1",
                time: "00:00:01",
                startTime: 0.8,
                endTime: 3.5,
                speaker: "Speaker A",
                ipa: "ˈtja.a",
                meaning: "market / tianguis",
                confidence: 93,
                culturalContext: "The weekly market (tianguis) is central to Mixtec community life and economic exchange.",
            },
            {
                id: "seg-mk2",
                time: "00:00:05",
                startTime: 4.2,
                endTime: 7.9,
                speaker: "Speaker A",
                ipa: "ˈku.ʔu.n ˈtja.a",
                meaning: "go to market",
                confidence: 88,
                culturalContext: "",
            },
            {
                id: "seg-mk3",
                time: "00:00:10",
                startTime: 9.5,
                endTime: 14.0,
                speaker: "Speaker B",
                ipa: "ˈna.sa ˈku.ʔu.n",
                meaning: "how much does it cost?",
                confidence: 82,
                culturalContext: "Price negotiation is expected and considered a social interaction, not confrontational.",
            },
            {
                id: "seg-mk4",
                time: "00:00:17",
                startTime: 16.3,
                endTime: 21.5,
                speaker: "Speaker A",
                ipa: "ˈu.ʃi ˈpe.so",
                meaning: "ten pesos",
                confidence: 90,
                culturalContext: "Spanish loanword 'peso' is fully integrated into Mixtec commerce vocabulary.",
            },
            {
                id: "seg-mk5",
                time: "00:00:25",
                startTime: 24.0,
                endTime: 28.8,
                speaker: "Speaker B",
                ipa: "ˈta.tʃi ˈi.ni",
                meaning: "thank you very much",
                confidence: 79,
                culturalContext: "Lower confidence due to overlapping speech. The phrase is a common expression of gratitude.",
            },
        ],
    },
    {
        id: "demo-lakota-kinship",
        fileName: "lakota_kinship_terms_001.wav",
        language: "Lakota",
        segmentCount: 4,
        avgConfidence: 90,
        durationSeconds: 28.0,
        model: "Allosaurus (uni2005)",
        createdAt: "2026-03-02T09:00:00.000Z",
        segments: [
            {
                id: "seg-l1",
                time: "00:00:02",
                startTime: 1.5,
                endTime: 5.0,
                speaker: "Elder Mary",
                ipa: "iˈna",
                meaning: "mother",
                confidence: 95,
                culturalContext: "Lakota kinship terms are relational — 'ina' specifically means 'my mother'. The possessive is built into the word.",
            },
            {
                id: "seg-l2",
                time: "00:00:07",
                startTime: 6.2,
                endTime: 10.5,
                speaker: "Elder Mary",
                ipa: "aˈte",
                meaning: "father",
                confidence: 94,
                culturalContext: "Again, possessive is inherent. 'Ate' = 'my father'. Third person would use a different form.",
            },
            {
                id: "seg-l3",
                time: "00:00:13",
                startTime: 12.0,
                endTime: 17.8,
                speaker: "Elder Mary",
                ipa: "tʰuŋˈka.ʃi.la",
                meaning: "grandfather",
                confidence: 88,
                culturalContext: "Thunkášila also carries deep spiritual significance — it is used to address Wakan Tanka (the Great Spirit) in prayer.",
            },
            {
                id: "seg-l4",
                time: "00:00:20",
                startTime: 19.5,
                endTime: 24.2,
                speaker: "Elder Mary",
                ipa: "uŋˈtʃi",
                meaning: "grandmother",
                confidence: 83,
                culturalContext: "Grandmothers hold a position of great respect in Lakota society as keepers of knowledge and tradition.",
            },
        ],
    },
];
